//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public string type { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public decimal grossSalary { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> UserID_Fk { get; set; }
        public Nullable<int> siteFK { get; set; }
        public Nullable<int> PositionFK { get; set; }
        public Nullable<decimal> FixAllowance { get; set; }
        public Nullable<decimal> Gas { get; set; }
        public Nullable<decimal> Tel { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual Site Site { get; set; }
    }
}
