//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceEntities : DbContext
    {
        public AttendanceEntities()
            : base("name=AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<tb_appraisal> tb_appraisal { get; set; }
        public virtual DbSet<tb_attendance> tb_attendance { get; set; }
        public virtual DbSet<tb_attendance_attachment> tb_attendance_attachment { get; set; }
        public virtual DbSet<tb_customer> tb_customer { get; set; }
        public virtual DbSet<tb_Department> tb_Department { get; set; }
        public virtual DbSet<tb_file> tb_file { get; set; }
        public virtual DbSet<tb_fingerprint> tb_fingerprint { get; set; }
        public virtual DbSet<tb_generate_type> tb_generate_type { get; set; }
        public virtual DbSet<tb_Group_Position> tb_Group_Position { get; set; }
        public virtual DbSet<tb_OT> tb_OT { get; set; }
        public virtual DbSet<tb_OT_Detail> tb_OT_Detail { get; set; }
        public virtual DbSet<tb_Payroll> tb_Payroll { get; set; }
        public virtual DbSet<tb_PayrollDetail> tb_PayrollDetail { get; set; }
        public virtual DbSet<tb_Project> tb_Project { get; set; }
        public virtual DbSet<tb_province> tb_province { get; set; }
        public virtual DbSet<tb_PublicHoliday> tb_PublicHoliday { get; set; }
        public virtual DbSet<TimeSchedule> TimeSchedules { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounters { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Hash> Hashes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobParameter> JobParameters { get; set; }
        public virtual DbSet<JobQueue> JobQueues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
