//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeMaster()
        {
            this.Contracts = new HashSet<Contract>();
            this.tb_OT_Detail = new HashSet<tb_OT_Detail>();
            this.tb_Payroll = new HashSet<tb_Payroll>();
            this.tb_file = new HashSet<tb_file>();
        }
    
        public int id { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> Position { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ChildNumber { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public Nullable<int> project { get; set; }
        public Nullable<int> department { get; set; }
        public string FirstNameKH { get; set; }
        public string LastNameKH { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string EmergencyPhoneNumber { get; set; }
        public string MarritalStatus { get; set; }
        public string PresentAddress { get; set; }
        public string PermanetAddress { get; set; }
        public string LevelEducation { get; set; }
        public string FieldofEducation { get; set; }
        public string SpouseGuardian { get; set; }
        public string SpouseOccupation { get; set; }
        public string Working_Status { get; set; }
        public string BankAccount { get; set; }
        public string LGTFund { get; set; }
        public string Remark { get; set; }
        public string IDCardNo { get; set; }
        public Nullable<decimal> Gas { get; set; }
        public Nullable<decimal> Tel { get; set; }
        public string NFFS { get; set; }
        public Nullable<int> RecruitmentBase { get; set; }
        public Nullable<decimal> fixallowance { get; set; }
        public string RTS_reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual tb_Department tb_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OT_Detail> tb_OT_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Payroll> tb_Payroll { get; set; }
        public virtual tb_province tb_province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_file> tb_file { get; set; }
    }
}
