//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> status { get; set; }
        public string description { get; set; }
        public string Owner { get; set; }
        public string location { get; set; }
        public Nullable<int> project_fk { get; set; }
        public Nullable<decimal> siteAllowance { get; set; }
        public Nullable<int> Province_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual tb_Project tb_Project { get; set; }
        public virtual tb_province tb_province { get; set; }
    }
}
