//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_attendance
    {
        public int id { get; set; }
        public string empID { get; set; }
        public string fpID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> status { get; set; }
        public string overtime_in { get; set; }
        public string overtime_out { get; set; }
        public string new_state { get; set; }
        public Nullable<int> ref_id { get; set; }
        public Nullable<System.DateTime> attendance_date { get; set; }
    }
}
