//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer
    {
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public string cus_tel { get; set; }
        public string cus_address { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
