//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fingerprint
    {
        public int id { get; set; }
        public string fp_id { get; set; }
        public string fp_ipaddress { get; set; }
        public string fp_name { get; set; }
        public string fp_location { get; set; }
        public bool fp_status { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> site_fk { get; set; }
    }
}
