//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_file
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string fileext { get; set; }
        public string filecode { get; set; }
        public Nullable<int> userID_fk { get; set; }
        public string filetype { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
