//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Group_Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Group_Position()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int id { get; set; }
        public string GP_name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> status { get; set; }
        public string Level { get; set; }
        public Nullable<decimal> Gas { get; set; }
        public Nullable<decimal> Tel { get; set; }
        public Nullable<decimal> FixAllowance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
    }
}
