//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OT_Detail
    {
        public int id { get; set; }
        public string M_Hours { get; set; }
        public string A_Hours { get; set; }
        public Nullable<int> OT_Hours { get; set; }
        public System.DateTime createdat { get; set; }
        public Nullable<int> Emp_FK { get; set; }
        public Nullable<int> OT_FK { get; set; }
        public Nullable<int> Site_fk { get; set; }
        public string PM_remark { get; set; }
        public string HR_remark { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual tb_OT tb_OT { get; set; }
    }
}
