//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_OT()
        {
            this.tb_appraisal = new HashSet<tb_appraisal>();
            this.tb_OT_Detail = new HashSet<tb_OT_Detail>();
        }
    
        public int OT_ID { get; set; }
        public System.DateTime Created_at { get; set; }
        public string Created_by { get; set; }
        public string Status { get; set; }
        public System.DateTime OT_Date { get; set; }
        public Nullable<int> Project_fk { get; set; }
        public Nullable<int> Site_fk { get; set; }
        public string PM_Remark { get; set; }
        public string Hr_Approve { get; set; }
        public string HR_Remark { get; set; }
        public Nullable<int> GenerateType { get; set; }
        public string OT_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_appraisal> tb_appraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OT_Detail> tb_OT_Detail { get; set; }
    }
}
