//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PublicHoliday
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> modifiedat { get; set; }
        public string modifiedby { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
