//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Payroll
    {
        public string id { get; set; }
        public Nullable<int> payroll_detaile_FK { get; set; }
        public Nullable<decimal> basicSalary { get; set; }
        public string EmpDepartment { get; set; }
        public string EmpSite { get; set; }
        public Nullable<int> empID_Fk { get; set; }
        public Nullable<decimal> TaxDeductible { get; set; }
        public Nullable<decimal> OTH { get; set; }
        public Nullable<decimal> ActualWork { get; set; }
        public Nullable<decimal> CashAllowance { get; set; }
        public Nullable<decimal> OtherCashAllowance { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> BonusIncentive { get; set; }
        public Nullable<decimal> Deductale { get; set; }
        public Nullable<int> Site_FK { get; set; }
        public Nullable<decimal> TotalGrossBenefitThisMonth { get; set; }
        public Nullable<System.DateTime> PayrollDate { get; set; }
        public Nullable<decimal> OTMoney { get; set; }
        public Nullable<decimal> TaxOnTotalBenefit { get; set; }
        public Nullable<decimal> ThisMonthGrossSalary { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual tb_PayrollDetail tb_PayrollDetail { get; set; }
    }
}
