//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcelToDatabase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PayrollDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PayrollDetail()
        {
            this.tb_Payroll = new HashSet<tb_Payroll>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public string PaidBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string AccManag_Status { get; set; }
        public string FinalPayroll_Status { get; set; }
        public System.DateTime PayrollMonth { get; set; }
        public string AccManag_Reason { get; set; }
        public string FinalPayroll_Reason { get; set; }
        public string AccManag_Approvedby { get; set; }
        public string FinalPayroll_Approvedby { get; set; }
        public string GenerateType { get; set; }
        public Nullable<bool> BonusIncentiveCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Payroll> tb_Payroll { get; set; }
    }
}
